--- a	2023-09-28 18:43:34.083370964 +0100
+++ b	2023-09-28 18:43:34.095371465 +0100
@@ -20,7 +20,7 @@
 diff --git a/otherlibs/systhreads/thread.ml b/otherlibs/systhreads/thread.ml
 --- a/otherlibs/systhreads/thread.ml
 +++ b/otherlibs/systhreads/thread.ml
-@@ -29,7 +29,6 @@ external yield : unit -> unit = "caml_thread_yield"
+@@ -31,7 +31,6 @@ external yield : unit -> unit = "caml_thread_yield"
  external self : unit -> t = "caml_thread_self" [@@noalloc]
  external id : t -> int = "caml_thread_id" [@@noalloc]
  external join : t -> unit = "caml_thread_join"
@@ -28,7 +28,7 @@
  
  (* For new, make sure the function passed to thread_new never
     raises an exception. *)
-@@ -42,18 +41,25 @@ let uncaught_exception_handler = ref default_uncaught_exception_handler
+@@ -44,18 +43,25 @@ let uncaught_exception_handler = ref default_uncaught_exception_handler
  
  let set_uncaught_exception_handler fn = uncaught_exception_handler := fn
  
@@ -56,7 +56,7 @@
            Printf.eprintf
              "Thread %d killed on uncaught exception %s\n"
              (id (self ())) (Printexc.to_string exn);
-@@ -65,8 +71,7 @@ let create fn arg =
+@@ -67,8 +73,7 @@ let create fn arg =
            flush stderr)
  
  let exit () =
@@ -121,32 +121,32 @@
  Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
  Called from Backtrace_systhreads.thread_func in file "backtrace_systhreads.ml", line 14, characters 6-37
  Re-raised at Backtrace_systhreads.thread_func in file "backtrace_systhreads.ml", line 18, characters 5-14
--Called from Thread.create.(fun) in file "thread.ml", line 49, characters 8-14
-+Called from Thread.create.(fun) in file "thread.ml", line 50, characters 8-14
+-Called from Thread.create.(fun) in file "thread.ml", line 51, characters 8-14
++Called from Thread.create.(fun) in file "thread.ml", line 49, characters 8-14
  Thread 3 killed on uncaught exception Failure("1")
  Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
  Called from Backtrace_systhreads.thread_func in file "backtrace_systhreads.ml", line 14, characters 6-37
  Re-raised at Backtrace_systhreads.thread_func in file "backtrace_systhreads.ml", line 18, characters 5-14
--Called from Thread.create.(fun) in file "thread.ml", line 49, characters 8-14
-+Called from Thread.create.(fun) in file "thread.ml", line 50, characters 8-14
+-Called from Thread.create.(fun) in file "thread.ml", line 51, characters 8-14
++Called from Thread.create.(fun) in file "thread.ml", line 49, characters 8-14
  Thread 4 killed on uncaught exception Failure("2")
  Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
  Called from Backtrace_systhreads.thread_func in file "backtrace_systhreads.ml", line 14, characters 6-37
  Re-raised at Backtrace_systhreads.thread_func in file "backtrace_systhreads.ml", line 18, characters 5-14
--Called from Thread.create.(fun) in file "thread.ml", line 49, characters 8-14
-+Called from Thread.create.(fun) in file "thread.ml", line 50, characters 8-14
+-Called from Thread.create.(fun) in file "thread.ml", line 51, characters 8-14
++Called from Thread.create.(fun) in file "thread.ml", line 49, characters 8-14
  Thread 5 killed on uncaught exception Failure("3")
  Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
  Called from Backtrace_systhreads.thread_func in file "backtrace_systhreads.ml", line 14, characters 6-37
  Re-raised at Backtrace_systhreads.thread_func in file "backtrace_systhreads.ml", line 18, characters 5-14
--Called from Thread.create.(fun) in file "thread.ml", line 49, characters 8-14
-+Called from Thread.create.(fun) in file "thread.ml", line 50, characters 8-14
+-Called from Thread.create.(fun) in file "thread.ml", line 51, characters 8-14
++Called from Thread.create.(fun) in file "thread.ml", line 49, characters 8-14
  Thread 1 killed on uncaught exception Failure("backtrace")
  Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
  Called from Backtrace_systhreads.thread_backtrace in file "backtrace_systhreads.ml", line 22, characters 6-27
  Re-raised at Backtrace_systhreads.thread_backtrace in file "backtrace_systhreads.ml", line 26, characters 5-14
--Called from Thread.create.(fun) in file "thread.ml", line 49, characters 8-14
-+Called from Thread.create.(fun) in file "thread.ml", line 50, characters 8-14
+-Called from Thread.create.(fun) in file "thread.ml", line 51, characters 8-14
++Called from Thread.create.(fun) in file "thread.ml", line 49, characters 8-14
 diff --git a/testsuite/tests/backtrace/callstack.reference b/testsuite/tests/backtrace/callstack.reference
 --- a/testsuite/tests/backtrace/callstack.reference
 +++ b/testsuite/tests/backtrace/callstack.reference
@@ -154,8 +154,8 @@
  Called from Callstack.f1 in file "callstack.ml", line 12, characters 27-32
  Called from Callstack.f2 in file "callstack.ml", line 13, characters 27-32
  Called from Callstack.f3 in file "callstack.ml", line 14, characters 27-32
--Called from Thread.create.(fun) in file "thread.ml", line 49, characters 8-14
-+Called from Thread.create.(fun) in file "thread.ml", line 50, characters 8-14
+-Called from Thread.create.(fun) in file "thread.ml", line 51, characters 8-14
++Called from Thread.create.(fun) in file "thread.ml", line 49, characters 8-14
 diff --git a/testsuite/tests/lib-threads/bufchan.ml b/testsuite/tests/lib-threads/bufchan.ml
 --- a/testsuite/tests/lib-threads/bufchan.ml
 +++ b/testsuite/tests/lib-threads/bufchan.ml
@@ -248,21 +248,21 @@
 @@ -1,12 +1,15 @@
  Thread 1 killed on uncaught exception Uncaught_exception_handler.CallbackExn
  Raised at Uncaught_exception_handler.fn in file "uncaught_exception_handler.ml", line 28, characters 12-113
--Called from Thread.create.(fun) in file "thread.ml", line 49, characters 8-14
-+Called from Thread.create.(fun) in file "thread.ml", line 50, characters 8-14
+-Called from Thread.create.(fun) in file "thread.ml", line 51, characters 8-14
++Called from Thread.create.(fun) in file "thread.ml", line 49, characters 8-14
  [thread 2] caught Uncaught_exception_handler.CallbackExn
  Raised at Uncaught_exception_handler.fn in file "uncaught_exception_handler.ml", line 28, characters 12-113
--Called from Thread.create.(fun) in file "thread.ml", line 49, characters 8-14
-+Called from Thread.create.(fun) in file "thread.ml", line 50, characters 8-14
+-Called from Thread.create.(fun) in file "thread.ml", line 51, characters 8-14
++Called from Thread.create.(fun) in file "thread.ml", line 49, characters 8-14
  Thread 2 killed on uncaught exception Uncaught_exception_handler.CallbackExn
  Raised at Uncaught_exception_handler.fn in file "uncaught_exception_handler.ml", line 28, characters 12-113
--Called from Thread.create.(fun) in file "thread.ml", line 49, characters 8-14
-+Called from Thread.create.(fun) in file "thread.ml", line 50, characters 8-14
+-Called from Thread.create.(fun) in file "thread.ml", line 51, characters 8-14
++Called from Thread.create.(fun) in file "thread.ml", line 49, characters 8-14
  Thread 2 uncaught exception handler raised Uncaught_exception_handler.UncaughtHandlerExn
 -Raised at Uncaught_exception_handler.handler in file "uncaught_exception_handler.ml", line 26, characters 2-26
--Called from Thread.create.(fun) in file "thread.ml", line 55, characters 10-41
+-Called from Thread.create.(fun) in file "thread.ml", line 57, characters 10-41
 +Raised at Uncaught_exception_handler.handler in file "uncaught_exception_handler.ml", line 26, characters 2-17
-+Called from Thread.create.(fun) in file "thread.ml", line 59, characters 10-41
++Called from Thread.create.(fun) in file "thread.ml", line 58, characters 10-41
 +[thread 3] caught Uncaught_exception_handler.CallbackExn
 +Raised at Uncaught_exception_handler.fn in file "uncaught_exception_handler.ml", line 28, characters 12-113
-+Called from Thread.create.(fun) in file "thread.ml", line 50, characters 8-14
++Called from Thread.create.(fun) in file "thread.ml", line 49, characters 8-14
