Thread 1 killed on uncaught exception Uncaught_exception_handler.CallbackExn
Raised at Uncaught_exception_handler.fn in file "uncaught_exception_handler.ml", line 28, characters 12-113
<<<<<<< HEAD
Called from Thread.create.(fun) in file "thread.ml", line 51, characters 8-14
||||||| parent of d84d773022 (Reimplement Thread.exit using the Thread.Exit exception (PR#10935))
Called from Thread.create.(fun) in file "thread.ml", line 49, characters 8-14
=======
Called from Thread.create.(fun) in file "thread.ml", line 50, characters 8-14
>>>>>>> d84d773022 (Reimplement Thread.exit using the Thread.Exit exception (PR#10935))
[thread 2] caught Uncaught_exception_handler.CallbackExn
Raised at Uncaught_exception_handler.fn in file "uncaught_exception_handler.ml", line 28, characters 12-113
<<<<<<< HEAD
Called from Thread.create.(fun) in file "thread.ml", line 51, characters 8-14
||||||| parent of d84d773022 (Reimplement Thread.exit using the Thread.Exit exception (PR#10935))
Called from Thread.create.(fun) in file "thread.ml", line 49, characters 8-14
=======
Called from Thread.create.(fun) in file "thread.ml", line 50, characters 8-14
>>>>>>> d84d773022 (Reimplement Thread.exit using the Thread.Exit exception (PR#10935))
Thread 2 killed on uncaught exception Uncaught_exception_handler.CallbackExn
Raised at Uncaught_exception_handler.fn in file "uncaught_exception_handler.ml", line 28, characters 12-113
<<<<<<< HEAD
Called from Thread.create.(fun) in file "thread.ml", line 51, characters 8-14
||||||| parent of d84d773022 (Reimplement Thread.exit using the Thread.Exit exception (PR#10935))
Called from Thread.create.(fun) in file "thread.ml", line 49, characters 8-14
=======
Called from Thread.create.(fun) in file "thread.ml", line 50, characters 8-14
>>>>>>> d84d773022 (Reimplement Thread.exit using the Thread.Exit exception (PR#10935))
Thread 2 uncaught exception handler raised Uncaught_exception_handler.UncaughtHandlerExn
<<<<<<< HEAD
Raised at Uncaught_exception_handler.handler in file "uncaught_exception_handler.ml", line 26, characters 2-26
Called from Thread.create.(fun) in file "thread.ml", line 57, characters 10-41
||||||| parent of d84d773022 (Reimplement Thread.exit using the Thread.Exit exception (PR#10935))
Raised at Uncaught_exception_handler.handler in file "uncaught_exception_handler.ml", line 26, characters 2-26
Called from Thread.create.(fun) in file "thread.ml", line 55, characters 10-41
=======
Raised at Uncaught_exception_handler.handler in file "uncaught_exception_handler.ml", line 26, characters 2-17
Called from Thread.create.(fun) in file "thread.ml", line 59, characters 10-41
[thread 3] caught Uncaught_exception_handler.CallbackExn
Raised at Uncaught_exception_handler.fn in file "uncaught_exception_handler.ml", line 28, characters 12-113
Called from Thread.create.(fun) in file "thread.ml", line 50, characters 8-14
>>>>>>> d84d773022 (Reimplement Thread.exit using the Thread.Exit exception (PR#10935))
